.coveragerc, .gitignore, .travis.yml, README.rst, setup.py, tox.ini, wagtailinventory/fixtures/test_blocks.json, wagtailinventory/forms.py, wagtailinventory/helpers.py, wagtailinventory/management/commands/block_inventory.py, wagtailinventory/models.py, wagtailinventory/tests/settings.py, wagtailinventory/tests/test_helpers.py, wagtailinventory/tests/test_models.py, wagtailinventory/tests/test_wagtail_hooks.py, wagtailinventory/tests/testapp/blocks.py, wagtailinventory/tests/testapp/migrations/0001_initial.py, wagtailinventory/tests/testapp/migrations/0002_nested_stream_block_page.py, wagtailinventory/tests/testapp/migrations/0003_single_content_block_optional.py, wagtailinventory/tests/testapp/models.py, wagtailinventory/tests/urls.py, wagtailinventory/urls.py, wagtailinventory/views.py, wagtailinventory/wagtail_hooks.py
This change adds support for Django 2.0 and Wagtail 2.0/2.1 to this package. The README has been updated to reflect the change.
A `.coveragerc` file has been added to more helpfully limit test code coverage and the test runner now dumps coverage to console for easier reviewing. These changes also include a new test fixture for easier testing of blocks.
Fixes #8.
To verify this change against Django 2.0 and Wagtail 2.0:
1. Create a new isolated virtualenv with Python 3.6 named `testwi`.
```
$ mkvirtualenv --no-site-packages --python=python3.6 testwi
```
2. Install this PR into the virtualenv. Pulls in Wagtail/Django 2. [This open issue](https://github.com/python-pillow/Pillow/issues/3068) means that at least for now on Macs, you need to override the version of Pillow that gets pulled in …
=> Adds Django 2.0 and Wagtail 2.0/2.1 support

wagtailinventory/forms.py, wagtailinventory/tests/test_forms.py
This commit explicilty orders blocks alphabetically in the Wagtail admin search form. Previously the ordering was unspecified and so was aribtrarily ordered depending on the database backend.
Fixes #12.
=> Alphabetically order blocks in search form

wagtailinventory/templates/wagtailinventory/search.html, wagtailinventory/views.py
The changes in #11 to add Django/Wagtail 2.x support made a slight change to how the wagtail-inventory search URL is defined:
https://github.com/cfpb/wagtail-inventory/commit/5900a7993ba5c086206d644f32d144192678effc#diff-e5cdc1d4255de591a575368291bee269L30
Unfortunately, this broke pagination of wagtail-inventory results in the admin. In version 0.4.2 and previous, the admin page would erroneously load with any URL, e.g. /admin/inventory/anything?foo=bar... Along with this, the use of [`replace_page_in_query`](https://github.com/wagtail/wagtail/blob/f0eef2fc88043ba627b89125876f1cfe53b7fc51/wagtail/utils/pagination.py#L23) to generate page URLs wasn't creating proper URLs. It so happened that the combination of these two things made working (if ugly) URLs for pagination, but the change in …
=> Fix broken pagination in search results

.travis.yml, README.rst, setup.py, tox.ini, wagtailinventory/management/commands/block_inventory.py, wagtailinventory/tests/test_views.py, wagtailinventory/views.py
This change adds support for Wagtail 2.6. It also corrects a deprecation warning that starts appearing in Wagtail 2.5 due to deprecation of `wagtail.utils.pagination`. For version 2.5 or newer, we instead use Django's paginator [as recommended by the Wagtail docs](https://docs.wagtail.io/en/latest/releases/2.5.html#changes-to-admin-pagination-helpers).
Fixes #22.
=> Add support for Wagtail 2.6

.travis.yml, README.rst, setup.py, tox.ini
Support production version of Python 3.6 and latest version of Python 3.8
Support latest version of Wagtail 2.8
Remove Python 2.7 and add Python 3.8 to:
* README.rst
* setup.py
* tox.ini
* travis.yml
Add support for Wagtail 2.8 to `tox.ini`, `setup.py`, and `travis.yml`
Testing
$ tox
```
...
py36-dj111-wag113: commands succeeded
py36-dj111-wag23: commands succeeded
py36-dj111-wag20: commands succeeded
py36-dj20-wag20: commands succeeded
py36-dj20-wag23: commands succeeded
py36-dj20-wag28: commands succeeded
py36-dj22-wag28: commands succeeded
py38-dj20-wag28: commands succeeded
py38-dj22-wag28: commands succeeded
flake8: commands succeeded
congratulations :)
```
=> Support Wagtail 2.3

README.rst
#25 made some edits to the README, and added a link in Markdown format, where it should have instead been in RST format. This commit fixes that link.
=> Fix broken README link

.travis.yml, CONTRIBUTING.md, README.rst, pyproject.toml, setup.py, tox.ini, wagtailinventory/forms.py, wagtailinventory/helpers.py, wagtailinventory/management/commands/block_inventory.py, wagtailinventory/migrations/0001_initial.py, wagtailinventory/models.py, wagtailinventory/tests/settings.py, wagtailinventory/tests/test_forms.py, wagtailinventory/tests/test_helpers.py, wagtailinventory/tests/test_models.py, wagtailinventory/tests/test_views.py, wagtailinventory/tests/testapp/blocks.py, wagtailinventory/tests/testapp/migrations/0001_initial.py, wagtailinventory/tests/testapp/migrations/0002_nested_stream_block_page.py, wagtailinventory/tests/testapp/migrations/0003_single_content_block_optional.py, wagtailinventory/tests/testapp/models.py, wagtailinventory/tests/urls.py, wagtailinventory/urls.py, wagtailinventory/views.py, wagtailinventory/wagtail_hooks.py
Support for Django 2.2 imports
Add black to tox
Support for Wagtail 1.13 in tox and travis
`from __future__ import absolute_import, unicode_literals`
=> Remove Wagtail 1.13 support, add Django 2.2 import support, and add Black for autoformatting

.travis.yml, README.rst, setup.py, tox.ini, wagtailinventory/models.py, wagtailinventory/tests/test_views.py
We should probably only pin Wagtail in this application, and support
the version range for Django that our Wagtail version specifies.
=> Remove the Django requirement from this application

.travis.yml, README.rst, setup.py, tox.ini, wagtailinventory/tests/settings.py
This task is to pin tox environment on Wagtail 2.10 and ensure all tests pass.
There do not appear to be any upgrade considerations that we should be particularly concerned about with 2.10.
- wagtail 2.10 in tox.ini
=> Add support for latest Wagtail 2.10 release

README.rst
Swaps our build badge to use the Github Actions Build Badge.
- Travis CI Badge to Github Actions badge
=> Swap Travis badge for Github Actions Badge

.github/workflows/test.yml, setup.py, tox.ini, wagtailinventory/tests/settings.py
Configures our testing suite to test against the latest release of wagtail instead of a hard set maximum.
- wagtail < 2.11 -> wagtail < 3
- This is to align with our new goal of supporting new releases of wagtail based on tests passing, rather than manually confirming the library works.
=> Upgrade wagtail support to anything in this major version

.github/workflows/test.yml
GitHub Actions checks fail when run on forks of this repository ([example](https://github.com/cfpb/wagtail-inventory/pull/40/checks?check_run_id=1682697219) from #40) due to missing Coveralls configuration. This PR allows Coveralls to run successfully on forks.
Per the [Coveralls documentation](https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html), typically you need to set the environment variable `COVERALLS_REPO_TOKEN`, which we do on cfpb/wagtail-inventory as a repository secret. But forks don't have that variable defined, which leads to errors like this:
> Running on Github Actions but GITHUB_TOKEN is not set. Add "env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}" to your step config.
The Coveralls docs provide [another …
=> Allow Coveralls to run on forks of this repository

.github/workflows/test.yml, wagtailinventory/forms.py, wagtailinventory/templates/wagtailinventory/search.html
As reported in #39, the select dropdowns in the admin search form should have chevron icons to indicate that they can be selected.
This commit adds those icons by leveraging the built-in field template in the Wagtail admin ([wagtailadmin/shared/field.html](https://github.com/wagtail/wagtail/blob/master/wagtail/admin/templates/wagtailadmin/shared/field.html)). This also allows us to simplify the form and HTML code a bit.
This is an alternate approach than #40 that tries to leverage the built-in Wagtail template instead of using custom HTML.
=> Add missing chevron icons to select dropdowns

tox.ini, wagtailinventory/migrations/0002_pageblock_unique_constraint.py, wagtailinventory/models.py
More explicitly prevent the possibility of duplicate PageBlocks in the database.
An alternate approach to #44 and hopeful fix to #43, assuming it is caused by the lack of database constraint as suggested by the Django documentation [here](https://docs.djangoproject.com/en/dev/ref/models/querysets/#get-or-create):
> **Warning**
>
> [`get_or_create`] is atomic assuming that the database enforces uniqueness of the keyword arguments (see `unique` or `unique_together`). If the fields used in the keyword arguments do not have a uniqueness constraint, concurrent calls to this method may result in multiple rows with the same parameters being inserted.
=> Add UniqueConstraint on (page, block)

.github/workflows/test.yml, tox.ini
This change updates our tests to run against Python 3.9.
=> Update tests to Python 3.9

.github/workflows/test.yml, README.rst, setup.py, tox.ini, wagtailinventory/templates/wagtailinventory/_list_explore_inventory.html, wagtailinventory/templates/wagtailinventory/search.html
* Adds support for Wagtail 2.15
* Removes support for less than 2.15
* Adds Bulk Actions to search table results
* Bumps version to 1.4
* Drops Django 2.2 support
We tried to have a great way to support previous Wagtail versions, but with the `bulk_actions/footer.html` being moved in 2.15, it's a mess to support.
Closes #50
=> Wagtail 2.15 Support

.flake8, setup.cfg, tox.ini
"tox -e lint" was failing on this repository. There were multiple conflicting configurations for flake8: in .flake8, tox, and setup.cfg.
This commit simplifies so that the configuration only lives in .flake8, and works again even on the latest version of flake8.
=> Fix flake8 configuration

README.rst
We now use GitHub Actions instead of Travis CI.
=> Point README CI badge from Travis to GitHub

.github/workflows/test.yml, README.rst, setup.py, tox.ini
This commit adds support for Wagtail 4.1 and adds it to the testing matrix for tox and GitHub Actions.
=> Add support for Wagtail 4.1

.github/workflows/release.yml, .github/workflows/test.yml, .gitignore, .pre-commit-config.yaml, README.rst, setup.py, testmanage.py, tox.ini, wagtailinventory/forms.py, wagtailinventory/helpers.py, wagtailinventory/management/commands/block_inventory.py, wagtailinventory/models.py, wagtailinventory/tests/settings.py, wagtailinventory/tests/test_forms.py, wagtailinventory/tests/test_helpers.py, wagtailinventory/tests/test_models.py, wagtailinventory/tests/test_views.py, wagtailinventory/tests/test_wagtail_hooks.py, wagtailinventory/tests/testapp/blocks.py, wagtailinventory/tests/testapp/migrations/0001_initial.py, wagtailinventory/tests/testapp/migrations/0002_nested_stream_block_page.py, wagtailinventory/tests/testapp/migrations/0003_single_content_block_optional.py, wagtailinventory/tests/testapp/models.py, wagtailinventory/tests/urls.py, wagtailinventory/views.py, wagtailinventory/wagtail_hooks.py
- Updated tox testing and workflow actions
- Removed support for Wagtail versions < 4.1
- Suppress warnings
- Code cleanup
All tests run OK
```
Found 19 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
...................
----------------------------------------------------------------------
Ran 19 tests in 0.920s
OK
```
=> Draft: Wagtail 4.2 support

tox.ini
Our `tox -e interactive` here is broken — it's not running the `install_command` from `testenv` because there are no `deps` specified for the `interactive` env. This small change adds Django in `deps` and so the `install_command` runs and the interactive environment works.
=> Fix interactive tox env

.pre-commit-config.yaml, CONTRIBUTING.md, wagtailinventory/migrations/0001_initial.py, wagtailinventory/migrations/0002_pageblock_unique_constraint.py
Commit 792848dd4c4f864c1214b311ea43ce1a80cffc09 migrated this project from flake8 to ruff, but neglected to update the pre-commit config.
This commit does so. To test:
```
pip install pre-commit
pre-commit install
pre-commit run --all-files
```
=> Add ruff to pre-commit config

README.rst, wagtailinventory/tests/test_views.py, wagtailinventory/tests/test_wagtail_hooks.py, wagtailinventory/views.py, wagtailinventory/wagtail_hooks.py
Currently any Wagtail user with admin permissions may view the block inventory report. This commit adds the ability to leverage the existing wagtailinventory "view_pageblock" permission to grant this ability to non-admin users.
This permission can be granted in the standard Wagtail group view, listed as "Can view" for the "Page block" object type.
Closes #47; see also internal CFPB D&CP#349. Ping @csebianlander since I can't request your review here.
To test, run an interactive test session with `tox -e interactive`. First login as the admin user with credentials `admin` / `changeme`. Confirm that the block inventory exists in the Reports sidebar menu and that you can view it.
Then, create a new non-admin user at http://localhost:8000/admin/users/add/. Add this user to the existing …
=> Add ability to limit block inventory permission

.github/workflows/test.yml, .pre-commit-config.yaml, pyproject.toml, tox.ini, wagtailinventory/models.py
This change updates our tooling to make a few changes and updates:
- Use Ruff exclusively for formatting, linting, and import-sorting. Ruff can replace Black and isort, and is faster.
- Add Bandit for static security analysis.
- Move to pyproject.toml
- Add setuptools_scm for versioning. This will mean we don't have to manually update a version number in pyproject.toml.
- Run `ruff check --fix` for linting fixes
- Bumps the minimum version of Wagtail to 5.2, the latest LTS.
=> Update package tooling and boilerplate

.github/workflows/test.yml
As of September 2nd, using the `upload-artifact` GitHub Action no longer uploads hidden files by default:
https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breaking-changes-in-github-actions-runners/
This breaks uploading of `.coverage.*` files used to combine multiple coverage reports.
The `upload-artifact` README now includes [this guidance](https://github.com/actions/upload-artifact?tab=readme-ov-file#uploading-hidden-files) on including hidden files.
=> Fix missing coverage files in GitHub Actions
